/**
 * A small valid one-page PDF so seed sample files (notice attachments, download-centre files)
 * have something real to open and download. Always marked as samples in the content itself.
 */
export function samplePdf(title: string, note: string): Buffer {
  const lines = [
    'ASDRI - As-Sunnah Dawah & Research Institute',
    note,
    '',
    title,
    '',
    'This placeholder PDF was generated by the seed to demonstrate the',
    'file download. Replace it with the office’s real file.',
  ]
  const text = lines
    .map((line, i) => `BT /F1 ${i === 3 ? 13 : 10} Tf 56 ${742 - i * 22} Td (${line.replace(/[()\\]/g, '')}) Tj ET`)
    .join('\n')
  const content = `${text}\n0 0 0 RG 56 700 m 539 700 l S`
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  let pdf = '%PDF-1.4\n'
  const offsets: number[] = []
  objects.forEach((obj, i) => {
    offsets.push(pdf.length)
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`
  })
  const xrefStart = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`
  return Buffer.from(pdf, 'latin1')
}
