import type { SeedCourse } from './types'

// ─── 1. Preparatory Year for Specialization (PYS) ────────────────────────────────────────
export const preparatoryYearCourse: SeedCourse = {
  slug: 'preparatory-year-for-specialization',
  bn: {
    title: 'Preparatory Year for Specialization (PYS)',
    summary: 'এটি তরুণ ও মেধাবী আলেমদের জন্য গবেষণানির্ভর উচ্চশিক্ষা প্রোগ্রাম।',
    intro:
      'এটি তরুণ ও মেধাবী আলেমদের জন্য গবেষণানির্ভর উচ্চশিক্ষা প্রোগ্রাম। যোগ্য আলেমদের আধুনিক জ্ঞান-বিজ্ঞানে দক্ষ করে আন্তর্জাতিক মানের দাঈ ও গবেষক হিসেবে গড়ে তোলার লক্ষ্যে এই কোর্সটি চালু করা হয়েছে। বিশেষভাবে এই কোর্সটি কওমি মাদরাসা পড়ুয়া মেধাবী আলেমদের জন্য ডিজাইন করা হয়েছে, যাতে তারা সমসাময়িক চ্যালেঞ্জ মোকাবেলা করে ইসলামের দাওয়াহ দিতে পারেন।',
    formatDuration: '৩ বছর',
    formatBullets: [
      'Preparatory Year for Specialization (PYS) ১ বছর মেয়াদী কোর্স। এটি সবার জন্য বাধ্যতামূলক এবং তাখাসসুসের প্রস্তুতিমূলক বর্ষ হিসেবে বিবেচিত হবে।',
      'দ্বিতীয় ও প্রস্তুতিমূলক বর্ষ শেষে ফলাফল ও আগ্রহের ভিত্তিতে চূড়ান্তভাবে বিভাগ নির্বাচন করা হবে।',
      'নির্বাচিত বিভাগে ২ বছর মেয়াদী উচ্চশিক্ষা কোর্স করা যাবে।',
    ],
    specialisationsLead: 'পাঁচটি তাখাচ্ছুছ বিভাগ যথাক্রমে:',
    semesters: [
      {
        title: '১ম সেমিস্টার',
        subtitle: 'মূল কোর্সসমূহ (Core Courses)',
        note: '(এই কোর্সগুলো এই শিক্ষাক্রমের প্রধান একাডেমিক ভিত্তি। এগুলো নির্দিষ্ট একাডেমিক ক্রেডিট বহন করে, যা মোট ক্রেডিট ও সিজিপিএ (CGPA) অর্জনে ভূমিকা রাখে এবং প্রোগ্রামটি সফলভাবে সম্পন্ন করার জন্য সম্পন্ন করা বাধ্যতামূলক।)',
        sourceTotalCredits: 17,
        sourceTotalMarks: 600,
        rows: [
          {
            code: 'PYS 1101',
            title: 'Islam and Da‘wah',
            modules: ['Introduction to Islam', 'Introduction to Da‘wah'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1102',
            title: 'Introduction to Islamic Sciences',
            modules: ['Ulumul Quran', 'Ulumul Hadith', 'Usulul Fiqh'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1103',
            title: 'Islamic History and Civilization',
            modules: ['Islam in South Asia', 'Intellectual History of Islamic Civilization'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1104',
            title: 'Media and Society',
            modules: [
              'Media and Journalism in Global Political Context',
              'World Civilizations and Cultures',
              'Foundation of Politics & International Relations',
              'Legal Systems & General Jurisprudence',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1105',
            title: 'Critical Reading',
            modules: ['Critical Reading'],
            credits: 4,
            marks: 100,
          },
        ],
      },
      {
        title: '২য় সেমিস্টার',
        sourceTotalCredits: 19,
        sourceTotalMarks: 600,
        rows: [
          {
            code: 'PYS 1201',
            title: 'Human and Social Systems',
            modules: [
              'Psychology',
              'Sociology',
              'Economics & Islamic Finance',
              'Islamic Governance (Siyasah Shar‘iyyah)',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1202',
            title: 'Philosophy and Religion',
            modules: [
              'Introduction to Philosophy',
              'Modern Ideologies & Intellectual Trends',
              'Foundation of Comparative Religion',
            ],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1203',
            title: 'Basic Science',
            modules: [
              'Physics',
              'Chemistry',
              'Biology',
              'Astronomy',
              'Environmental Science',
              'Meteorology',
              'Electricity',
              'ICT',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1204',
            title: 'Research Methodology',
            modules: ['Research Methodology'],
            credits: 4,
            marks: 100,
          },
          { code: 'PYS 1205', title: 'Viva', credits: 2, marks: 100 },
        ],
      },
      {
        title: 'সম্পূরক কোর্সসমূহ (নন-ক্রেডিট বাধ্যতামূলক)',
        note: '(এই সম্পূরক কোর্সগুলো শিক্ষার্থীদের ভাষাগত, ডিজিটাল, গাণিতিক ও একাডেমিক দক্ষতা উন্নয়নের জন্য প্রণীত। কোর্সগুলো সম্পন্ন করা বাধ্যতামূলক এবং প্রাতিষ্ঠানিকভাবে মূল্যায়ন করা হলেও এর ফলাফল চূড়ান্ত ক্রেডিট বা সিজিপিএ (CGPA)-তে যুক্ত হয় না।)',
        sourceTotalHours: 500,
        sourceTotalMarks: 500,
        rows: [
          {
            code: 'PYS 1001',
            title: 'English Language',
            modules: ['English Language'],
            hours: 200,
            marks: 200,
          },
          {
            code: 'PYS 1002',
            title: 'Basic Computer',
            modules: ['MS Office'],
            hours: 100,
            marks: 100,
          },
          {
            code: 'PYS 1003',
            title: 'Basic Mathematics',
            modules: ['Basic Mathematics'],
            hours: 100,
            marks: 100,
          },
          {
            code: 'PYS 1004',
            title: 'Bangla Language',
            modules: ['Bangla Language'],
            hours: 100,
            marks: 100,
          },
        ],
      },
    ],
    sdpNote:
      '(এসডিপি (Student Development Program)-এর কার্যক্রমগুলো শিক্ষার্থীদের নৈতিকতা, নেতৃত্ব, যোগাযোগ দক্ষতা ও সামাজিক দায়িত্ববোধ বিকাশের জন্য বাধ্যতামূলক। তবে এসব কার্যক্রমের জন্য কোনো একাডেমিক ক্রেডিট বা সিজিপিএ (CGPA)-তে কোনো প্রভাব নেই।)',
  },
  en: {
    title: 'Preparatory Year for Specialization (PYS)',
    summary:
      '3-Year residential flagship program for talented young Ulama focusing on higher dawah & modern challenges.',
    intro:
      'A research-based programme of higher education for young, gifted ulama. It was launched to make qualified ulama adept in modern arts and sciences, shaping them into dawah workers and researchers of international standing. The course is designed specifically for gifted graduates of qawmi madrasas, so that they can answer contemporary challenges and carry the dawah of Islam.',
    formatDuration: '3 years',
    formatBullets: [
      'Preparatory Year for Specialization (PYS) is a one-year course. It is compulsory for everyone and counts as the preparatory year for specialisation.',
      'At the end of the second, preparatory year, the department is chosen finally on the basis of results and inclination.',
      'A two-year higher-education course can then be taken in the chosen department.',
    ],
    specialisationsLead: 'The five specialisation (takhasus) departments, in order:',
    semesters: [
      {
        title: 'Semester 1',
        subtitle: 'Core Courses',
        note: '(These courses are the programme’s main academic foundation. They carry defined academic credits, count towards the total credits and the CGPA, and must be completed to finish the programme.)',
        sourceTotalCredits: 17,
        sourceTotalMarks: 600,
        rows: [
          {
            code: 'PYS 1101',
            title: 'Islam and Da‘wah',
            modules: ['Introduction to Islam', 'Introduction to Da‘wah'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1102',
            title: 'Introduction to Islamic Sciences',
            modules: ['Ulumul Quran', 'Ulumul Hadith', 'Usulul Fiqh'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1103',
            title: 'Islamic History and Civilization',
            modules: ['Islam in South Asia', 'Intellectual History of Islamic Civilization'],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1104',
            title: 'Media and Society',
            modules: [
              'Media and Journalism in Global Political Context',
              'World Civilizations and Cultures',
              'Foundation of Politics & International Relations',
              'Legal Systems & General Jurisprudence',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1105',
            title: 'Critical Reading',
            modules: ['Critical Reading'],
            credits: 4,
            marks: 100,
          },
        ],
      },
      {
        title: 'Semester 2',
        sourceTotalCredits: 19,
        sourceTotalMarks: 600,
        rows: [
          {
            code: 'PYS 1201',
            title: 'Human and Social Systems',
            modules: [
              'Psychology',
              'Sociology',
              'Economics & Islamic Finance',
              'Islamic Governance (Siyasah Shar‘iyyah)',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1202',
            title: 'Philosophy and Religion',
            modules: [
              'Introduction to Philosophy',
              'Modern Ideologies & Intellectual Trends',
              'Foundation of Comparative Religion',
            ],
            credits: 3,
            marks: 100,
          },
          {
            code: 'PYS 1203',
            title: 'Basic Science',
            modules: [
              'Physics',
              'Chemistry',
              'Biology',
              'Astronomy',
              'Environmental Science',
              'Meteorology',
              'Electricity',
              'ICT',
            ],
            credits: 4,
            marks: 100,
          },
          {
            code: 'PYS 1204',
            title: 'Research Methodology',
            modules: ['Research Methodology'],
            credits: 4,
            marks: 100,
          },
          { code: 'PYS 1205', title: 'Viva', credits: 2, marks: 100 },
        ],
      },
      {
        title: 'Supplementary courses (non-credit, compulsory)',
        note: '(These supplementary courses develop students’ linguistic, digital, mathematical and academic skills. Completing them is compulsory and the institute assesses them, but their results do not count towards the final credits or the CGPA.)',
        sourceTotalHours: 500,
        sourceTotalMarks: 500,
        rows: [
          {
            code: 'PYS 1001',
            title: 'English Language',
            modules: ['English Language'],
            hours: 200,
            marks: 200,
          },
          {
            code: 'PYS 1002',
            title: 'Basic Computer',
            modules: ['MS Office'],
            hours: 100,
            marks: 100,
          },
          {
            code: 'PYS 1003',
            title: 'Basic Mathematics',
            modules: ['Basic Mathematics'],
            hours: 100,
            marks: 100,
          },
          {
            code: 'PYS 1004',
            title: 'Bangla Language',
            modules: ['Bangla Language'],
            hours: 100,
            marks: 100,
          },
        ],
      },
    ],
    sdpNote:
      '(The Student Development Program activities are compulsory for developing students’ character, leadership, communication skills and sense of social responsibility. They carry no academic credits and have no effect on the CGPA.)',
  },
  arabicTitle: 'السنة التمهيدية للتخصص',
  shortTitle: 'PYS',
  type: 'long',
  status: 'active',
  residential: 'residential',
  gender: 'male',
  specialisations: [
    { name: 'Dawah and Comparative Religion', arabicName: 'الدعوة و مقارنة الأديان' },
    { name: 'Quranic Sciences and Tafsir', arabicName: 'علوم القرآن والتفسير' },
    { name: 'Fiqh and Ifta', arabicName: 'الفقه والإفتاء' },
    { name: 'Islamic Economics', arabicName: 'الاقتصاد الإسلامي' },
    { name: 'History of Islam', arabicName: 'التاريخ الإسلامي' },
  ],
  sdpRows: [
    {
      title: 'Tarbiyah Sessions',
      objective: 'Character building & spiritual growth',
      activities: 'Weekly talk, reflection',
      hours: 30,
      outcome: 'Moral development',
    },
    {
      title: 'Short Courses',
      objective: 'Skill enhancement',
      activities: 'Workshops, assignments',
      hours: 40,
      outcome: 'Practical skills',
    },
    {
      title: 'Seminars & Workshops',
      objective: 'Exposure to experts',
      activities: 'Guest lecture, discussion',
      hours: 10,
      outcome: 'Knowledge expansion',
    },
    {
      title: 'Co-Curricular Activities',
      objective: 'Leadership & teamwork',
      activities: 'Group work, events',
      hours: 50,
      outcome: 'Soft skills',
    },
    {
      title: 'Mandatory Reading',
      objective: 'Reading habit development',
      activities: 'Book reading, review',
      hours: 20,
      outcome: 'Critical thinking',
    },
    {
      title: 'Community Service',
      objective: 'Social responsibility',
      activities: 'Field work, volunteering',
      hours: 30,
      outcome: 'Civic engagement',
    },
  ],
  featured: true,
  order: 10,
}
