import type { SeedCourse } from './types'

// ─── 5. Ramadan Dawah Training ──────────────────────────────────────────────────────────
export const ramadanDawahTraining: SeedCourse = {
  slug: 'ramadan-dawah-training',
  bn: {
    title: 'রমাদান উপলক্ষে দাওয়াহ প্রশিক্ষণ',
    summary:
      'এই বাস্তবতা বিবেচনায় নিয়ে উক্ত সংকট উত্তরণ এবং মুসলিম উম্মাহর বিবেক জাগ্রত করার লক্ষ্যে যুগের চ্যালেঞ্জ মোকাবিলায় সক্ষম, জ্ঞানসমৃদ্ধ ও দক্ষ দাঈ গড়ে তোলার উদ্দেশ্যে এই প্রশিক্ষণ কর্মসূচির আয়োজন করা হয়।',
    intro:
      'বাংলাদেশে দাওয়াহ অঙ্গনে কর্মরত অনেকের মধ্যে প্রায়োগিক দক্ষতার ঘাটতি পরিলক্ষিত হয়, যা কখনও কখনও সামগ্রিকভাবে আলেম সমাজের জন্য বিব্রতকর পরিস্থিতির সৃষ্টি করে। এই বাস্তবতা বিবেচনায় নিয়ে উক্ত সংকট উত্তরণ এবং মুসলিম উম্মাহর বিবেক জাগ্রত করার লক্ষ্যে যুগের চ্যালেঞ্জ মোকাবিলায় সক্ষম, জ্ঞানসমৃদ্ধ ও দক্ষ দাঈ গড়ে তোলার উদ্দেশ্যে এই প্রশিক্ষণ কর্মসূচির আয়োজন করা হয়।',
    objectives: [
      'দাওয়াহর জ্ঞান অর্জনে আগ্রহী সর্বসাধারণের জন্য একটি নির্ভরযোগ্য প্ল্যাটফর্ম তৈরি।',
      'কর্মজীবনের পাশাপাশি প্রত্যেক মুসলিমকে নিজ অঙ্গনে ইসলামের একজন কার্যকর দাঈ হিসেবে গড়ে তোলা।',
      'প্রায়োগিক ও যুগোপযোগী প্রশিক্ষণের মাধ্যমে দাওয়াহর দক্ষতা বৃদ্ধি করে সমসাময়িক চ্যালেঞ্জ মোকাবেলায় সক্ষম করা।',
    ],
    formatDuration: '২০ দিন',
    eligibility: [
      'কওমি থেকে তাকমীল, আলিয়া থেকে ফাযিল-কামিল এবং বিশ্ববিদ্যালয় থেকে অনার্স-মাস্টার্সে অন্তত ৭০% নম্বর পেয়ে উত্তীর্ণ',
    ],
    topicsLabel: 'প্রশিক্ষণের বিষয়সমূহ',
    topics: [
      'কনফ্লিক্ট ম্যানেজমেন্ট',
      'ইমোশনাল ইন্টেলিজেন্স',
      'ধর্মত্যাগ ও পশ্চিমা সংস্কৃতির বিভ্রম',
      'টাইম ম্যানেজমেন্ট',
      'ম্যানারস এন্ড এটিকেট',
      'পাবলিক স্পিকিং',
      'ইফেক্টিভ কমিউনিকেশন',
      'লিডারশিপ, দাওয়াহ ও মনস্তত্ত্ব',
      'দ্বীন প্রচারে মিডিয়া ও মাঠ : কিছু বিবেচনা',
      'প্রাচ্যবিদদের ইসলাম চর্চা ও পশ্চিমা আগ্রাসন',
      'অর্থনীতি, পুঁজিবাদ ও ইসলাম',
      'নবীদের দাওয়াতি পদ্ধতি',
      'দাঈর ব্যক্তিত্ব ও গুণাবলি',
      'সাইন্টিজম : ইসলাম ও বিজ্ঞানের সংঘাত/বিজ্ঞান ও বিজ্ঞানবাদ',
      'বাংলাদেশ ও ইসলাম : আত্মপরিচয়ের সন্ধানে',
      'সেকুলারিজম',
      'মুসলিম উম্মাহর পতনে বিশ্বের কী ক্ষতি হলো',
      'ইসলামে নারীর অধিকার ও নারীবাদী ফেতনা',
      'প্যারেন্টিং',
      'অমুসলিমদের মাঝে দাওয়াহ : পথ-পদ্ধতি',
      'কাদিয়ানি মতবাদ ও খতমে নবুওয়াত',
      'সংশয়বাদ ও নাস্তিক্যবাদ : মোকাবেলা এবং উত্তরণের উপায়',
      'LGBTQ ও জেন্ডার ফিতনা : ভয়াবহতা ও জরুরী নিবেদন',
      'ইসলামি ইতিহাসের ভৌগোলিক পরিচিতি',
      'দাওয়াহ ও মার্কেটিং',
    ],
  },
  en: {
    title: 'Ramadan Dawah Training',
    summary:
      '20-Day practical skill program covering contemporary issues, public speaking, and intellectual challenges.',
    intro:
      'A lack of practical skill is often seen among those working in dawah in Bangladesh, which sometimes creates embarrassing situations for the alem community as a whole. With this reality in view, this training programme is organised with the aim of raising capable, knowledgeable and skilled da‘is who can face the challenges of the age and awaken the conscience of the Muslim ummah.',
    objectives: [
      'To build a reliable platform for everyone eager to learn dawah.',
      'To shape every Muslim, alongside their working life, into an effective da‘i in their own circle.',
      'To make them able to face contemporary challenges by sharpening dawah skills through practical, up-to-date training.',
    ],
    formatDuration: '20 days',
    eligibility: [
      'Takmil from a qawmi madrasa, Fazil-Kamil from the Alia stream, or an honours or master’s degree passed with at least 70% marks.',
    ],
    topicsLabel: 'Topics covered',
    topics: [
      'Conflict management',
      'Emotional intelligence',
      'Apostasy and the illusions of Western culture',
      'Time management',
      'Manners and etiquette',
      'Public speaking',
      'Effective communication',
      'Leadership, dawah and psychology',
      'Media and the field in spreading the deen: some considerations',
      'Orientalist studies of Islam and Western aggression',
      'Economics, capitalism and Islam',
      'The dawah methods of the prophets',
      'The character and qualities of a da‘i',
      'Scientism: the clash of Islam and science / science and scientism',
      'Bangladesh and Islam: in search of identity',
      'Secularism',
      'What the world lost when the Muslim ummah declined',
      'Women’s rights in Islam and the feminist fitnah',
      'Parenting',
      'Dawah among non-Muslims: ways and methods',
      'The Qadiyani creed and the finality of prophethood',
      'Scepticism and atheism: confronting and overcoming them',
      'LGBTQ and gender fitnah: its gravity and an urgent appeal',
      'A geographic introduction to Islamic history',
      'Dawah and marketing',
    ],
  },
  type: 'short',
  status: 'active',
  residential: 'both',
  gender: 'male',
  featured: true,
  order: 50,
}
