/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    people: Person;
    courses: Course;
    notices: Notice;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    notices: NoticesSelect<false> | NoticesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bn' | 'en') | ('bn' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'impact-stats': ImpactStat;
    home: Home;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'impact-stats': ImpactStatsSelect<false> | ImpactStatsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: 'bn' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leadership, teachers and teams. A person appears on the leadership page when "leadership" is ticked, and in the faculty directory when "faculty" is ticked. Photos and biographies are optional; the public pages fall back to a monogram.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * Bangla name verbatim from the client document; English transliteration (editable, GAP-C5).
   */
  name: string;
  /**
   * Optional. A quiet head-and-shoulders photo; a monogram is shown while empty.
   */
  photo?: (number | null) | Media;
  roles: ('leadership' | 'faculty' | 'staff' | 'author')[];
  /**
   * e.g. চেয়ারম্যান, উস্তাজ, আরবি শিক্ষক
   */
  designation?: string | null;
  /**
   * A teacher can belong to more than one team (the source document lists one teacher under both Tajweed and English).
   */
  teams?:
    ('core' | 'arabic' | 'tajweed' | 'tarbiyah' | 'english' | 'bangla' | 'computer' | 'math' | 'science')[] | null;
  /**
   * Subjects this person teaches, as listed in the client document.
   */
  subjects?:
    | {
        subject: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. The profile page stays complete while empty.
   */
  bio?: string | null;
  /**
   * Private. Never shown publicly.
   */
  email?: string | null;
  /**
   * Private. Never shown publicly.
   */
  phone?: string | null;
  social?:
    | {
        platform: 'facebook' | 'youtube' | 'x' | 'linkedin' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show in the featured people section on the home page.
   */
  featuredOnHome?: boolean | null;
  /**
   * Sort order within lists (smaller first).
   */
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Programmes and trainings. Codes follow one scheme (e.g. PYS 1101, CCIS 101, PGD-DIS 1101: prefix, then year+semester, then number — GAP-C3). Semester totals shown on the site are computed from the rows; the totals printed in the client document are kept in the source total fields for reconciliation (GAP-C2).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Short code, e.g. PYS. Always Latin digits.
   */
  shortTitle?: string | null;
  /**
   * Arabic name, shown with lang="ar" under the title.
   */
  arabicTitle?: string | null;
  type: 'long' | 'short';
  /**
   * active = full course page. draft = announced but without content yet (shows a marked placeholder — GAP-C4). Named listingStatus: "status" collides with the draft system’s _status on the versions table.
   */
  listingStatus: 'active' | 'draft';
  /**
   * Sort order within the index (smaller first).
   */
  order?: number | null;
  /**
   * One sentence for index rows and the home programme cards. Bangla is an excerpt from the client document; keep it verbatim.
   */
  summary?: string | null;
  /**
   * কোর্স পরিচিতি — the course introduction, verbatim from the client document.
   */
  intro?: string | null;
  /**
   * লক্ষ্য-উদ্দেশ্য। Rendered as a ruled list.
   */
  objectives?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * কোর্সের ধরন — the summary facts shown in the page margin, plus any further notes from the document as ruled lines.
   */
  format?: {
    /**
     * e.g. ৩ বছর, ৬ মাস, ১৫ দিন (Bengali digits in Bangla).
     */
    durationLabel?: string | null;
    residential?: ('residential' | 'nonResidential' | 'both') | null;
    /**
     * Leave empty when the document does not say.
     */
    gender?: ('male' | 'female' | 'all') | null;
    /**
     * The remaining কোর্সের ধরন lines from the document, verbatim.
     */
    bullets?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * ভর্তির যোগ্যতা / আবেদন যোগ্যতা। Rendered as a ruled list.
   */
  eligibility?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * PYS: the five specialisation (takhasus) departments with their Arabic names.
   */
  specialisations?: {
    /**
     * Lead-in line as printed, e.g. পাঁচটি তাখাচ্ছুছ বিভাগ যথাক্রমে:
     */
    lead?: string | null;
    items?:
      | {
          name: string;
          arabicName?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * কোর্স কারিকুলাম — one entry per table in the document (semesters, the non-credit supplementary table). Totals are computed from the rows.
   */
  semesters?:
    | {
        /**
         * e.g. ১ম সেমিস্টার; leave empty when the document prints a single unlabelled table.
         */
        title?: string | null;
        subtitle?: string | null;
        /**
         * e.g. সময়কাল: ৬ মাস
         */
        durationLabel?: string | null;
        /**
         * The explanatory paragraph printed with the table, verbatim.
         */
        note?: string | null;
        /**
         * Credits printed in the document heading (GAP-C2, office reference only; the site computes the total).
         */
        sourceTotalCredits?: number | null;
        /**
         * Marks printed in the document heading (GAP-C2, office reference only; the site computes the total).
         */
        sourceTotalMarks?: number | null;
        /**
         * Hours printed in the document heading (GAP-C2, office reference only; the site computes the total).
         */
        sourceTotalHours?: number | null;
        rows?:
          | {
              /**
               * Always Latin digits (GAP-C3).
               */
              code?: string | null;
              title: string;
              modules?:
                | {
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              credits?: number | null;
              hours?: number | null;
              marks?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * শিক্ষার্থী উন্নয়ন কার্যক্রম (Student Development Programs) — the PYS non-credit activities table. Also shown on the Student Development page.
   */
  sdp?: {
    /**
     * The explanatory paragraph printed with the table, verbatim.
     */
    note?: string | null;
    rows?:
      | {
          title: string;
          hours?: number | null;
          objective?: string | null;
          activities?: string | null;
          outcome?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The trainings’ topic lists (Ramadan 25 topics, Arabic and Azan curricula).
   */
  topics?: {
    /**
     * Section heading as printed, e.g. প্রশিক্ষণের বিষয়সমূহ
     */
    label?: string | null;
    items?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * কোর্স সম্পন্নকারীদের পরবর্তী শিক্ষাক্রম ও কর্মপরিকল্পনা — the Diploma’s next-steps section.
   */
  outcomes?: {
    intro?: string | null;
    items?:
      | {
          heading: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Show in the six featured programmes on the home page.
   */
  featured?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The notice board. Statuses (নতুন / আবেদন চলছে / আবেদন শেষ) are computed from the dates and can be overridden per notice. The notices installed by the seed are SAMPLES written to show the board, filters and badges — replace them with the office’s real announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: number;
  title: string;
  category: 'admission' | 'recruitment' | 'academic' | 'general';
  /**
   * The notice itself. Keep it short; details belong in the attached PDF.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on the board and the notice page.
   */
  publishedAt?: string | null;
  /**
   * Start of the application/active window, if any.
   */
  activeFrom?: string | null;
  /**
   * End of the window; after this the notice shows আবেদন শেষ.
   */
  activeUntil?: string | null;
  /**
   * Leave empty to let the site compute the status from the dates. Set only when the office needs to force a badge.
   */
  statusOverride?: ('new' | 'active' | 'closed') | null;
  /**
   * The notice PDF (or doc) readers download. One-click download on the notice page.
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * Optional download label, e.g. বিজ্ঞপ্তি (PDF)
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * “অনলাইন ফরম পূরণ করুন” target for admission and recruitment notices. Full URL for external forms (Google Forms etc.), or a site path.
   */
  applyLink?: string | null;
  /**
   * Pin to the top of the board.
   */
  pinned?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'notices';
        value: number | Notice;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  roles?: T;
  designation?: T;
  teams?: T;
  subjects?:
    | T
    | {
        subject?: T;
        id?: T;
      };
  bio?: T;
  email?: T;
  phone?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  featuredOnHome?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  arabicTitle?: T;
  type?: T;
  listingStatus?: T;
  order?: T;
  summary?: T;
  intro?: T;
  objectives?:
    | T
    | {
        value?: T;
        id?: T;
      };
  format?:
    | T
    | {
        durationLabel?: T;
        residential?: T;
        gender?: T;
        bullets?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  eligibility?:
    | T
    | {
        value?: T;
        id?: T;
      };
  specialisations?:
    | T
    | {
        lead?: T;
        items?:
          | T
          | {
              name?: T;
              arabicName?: T;
              id?: T;
            };
      };
  semesters?:
    | T
    | {
        title?: T;
        subtitle?: T;
        durationLabel?: T;
        note?: T;
        sourceTotalCredits?: T;
        sourceTotalMarks?: T;
        sourceTotalHours?: T;
        rows?:
          | T
          | {
              code?: T;
              title?: T;
              modules?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              credits?: T;
              hours?: T;
              marks?: T;
              id?: T;
            };
        id?: T;
      };
  sdp?:
    | T
    | {
        note?: T;
        rows?:
          | T
          | {
              title?: T;
              hours?: T;
              objective?: T;
              activities?: T;
              outcome?: T;
              id?: T;
            };
      };
  topics?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  outcomes?:
    | T
    | {
        intro?: T;
        items?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
            };
      };
  featured?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  body?: T;
  publishedAt?: T;
  activeFrom?: T;
  activeUntil?: T;
  statusOverride?: T;
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  applyLink?: T;
  pinned?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Full institute name as shown in the header and footer.
   */
  name: string;
  /**
   * Short form for tight spaces (mobile header, browser tab).
   */
  shortName?: string | null;
  tagline?: string | null;
  /**
   * The Foundation relationship line, e.g. “আস-সুন্নাহ ফাউন্ডেশনের একটি শিক্ষাপ্রতিষ্ঠান”.
   */
  parentLine?: string | null;
  parentUrl?: string | null;
  /**
   * Optional. Until a logo exists the site uses a typographic wordmark.
   */
  logo?: (number | null) | Media;
  /**
   * Prospectus PDF for the hero button. Button is hidden while empty.
   */
  prospectus?: (number | null) | Media;
  phones?:
    | {
        /**
         * International format, e.g. +880 1805-437910
         */
        number: string;
        /**
         * e.g. সকাল ৯টা থেকে বিকাল ৫টা
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  addresses?:
    | {
        label: string;
        text: string;
        /**
         * Google Maps link or embed URL
         */
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'facebook' | 'youtube' | 'whatsapp' | 'telegram' | 'instagram' | 'x' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * QR code image shown in the footer for admission updates (REQ-CON-03).
   */
  admissionQr?: (number | null) | Media;
  otherWebsites?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  features?: {
    admissions?: boolean | null;
    donations?: boolean | null;
    zakatCalculator?: boolean | null;
    blog?: boolean | null;
    notices?: boolean | null;
    gallery?: boolean | null;
    downloads?: boolean | null;
    faq?: boolean | null;
    fatwa?: boolean | null;
    clarifications?: boolean | null;
    library?: boolean | null;
    books?: boolean | null;
    researchProjects?: boolean | null;
    videos?: boolean | null;
    news?: boolean | null;
    events?: boolean | null;
    comments?: boolean | null;
    sponsorship?: boolean | null;
    donorPortal?: boolean | null;
    recurring?: boolean | null;
    international?: boolean | null;
    campaigns?: boolean | null;
    studentPortal?: boolean | null;
    alumniPortal?: boolean | null;
    facebookFeed?: boolean | null;
    search?: boolean | null;
    /**
     * Login / Create account links in the header
     */
    accounts?: boolean | null;
    /**
     * Theme switch in the footer
     */
    darkMode?: boolean | null;
  };
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        /**
         * Path ("/academics/courses") or full URL
         */
        href: string;
        newTab?: boolean | null;
        /**
         * Hide when this module is off
         */
        feature?:
          | (
              | 'admissions'
              | 'donations'
              | 'zakatCalculator'
              | 'blog'
              | 'notices'
              | 'gallery'
              | 'downloads'
              | 'faq'
              | 'fatwa'
              | 'clarifications'
              | 'library'
              | 'books'
              | 'researchProjects'
              | 'videos'
              | 'news'
              | 'events'
              | 'sponsorship'
              | 'donorPortal'
              | 'studentPortal'
              | 'alumniPortal'
              | 'search'
              | 'accounts'
            )
          | null;
        children?:
          | {
              label: string;
              /**
               * Path ("/academics/courses") or full URL
               */
              href: string;
              newTab?: boolean | null;
              /**
               * Hide when this module is off
               */
              feature?:
                | (
                    | 'admissions'
                    | 'donations'
                    | 'zakatCalculator'
                    | 'blog'
                    | 'notices'
                    | 'gallery'
                    | 'downloads'
                    | 'faq'
                    | 'fatwa'
                    | 'clarifications'
                    | 'library'
                    | 'books'
                    | 'researchProjects'
                    | 'videos'
                    | 'news'
                    | 'events'
                    | 'sponsorship'
                    | 'donorPortal'
                    | 'studentPortal'
                    | 'alumniPortal'
                    | 'search'
                    | 'accounts'
                  )
                | null;
              /**
               * One short line under the label in the dropdown
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  utility?:
    | {
        label: string;
        /**
         * Path ("/academics/courses") or full URL
         */
        href: string;
        newTab?: boolean | null;
        /**
         * Hide when this module is off
         */
        feature?:
          | (
              | 'admissions'
              | 'donations'
              | 'zakatCalculator'
              | 'blog'
              | 'notices'
              | 'gallery'
              | 'downloads'
              | 'faq'
              | 'fatwa'
              | 'clarifications'
              | 'library'
              | 'books'
              | 'researchProjects'
              | 'videos'
              | 'news'
              | 'events'
              | 'sponsorship'
              | 'donorPortal'
              | 'studentPortal'
              | 'alumniPortal'
              | 'search'
              | 'accounts'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        /**
         * Column heading
         */
        label: string;
        links?:
          | {
              label: string;
              /**
               * Path ("/academics/courses") or full URL
               */
              href: string;
              newTab?: boolean | null;
              /**
               * Hide when this module is off
               */
              feature?:
                | (
                    | 'admissions'
                    | 'donations'
                    | 'zakatCalculator'
                    | 'blog'
                    | 'notices'
                    | 'gallery'
                    | 'downloads'
                    | 'faq'
                    | 'fatwa'
                    | 'clarifications'
                    | 'library'
                    | 'books'
                    | 'researchProjects'
                    | 'videos'
                    | 'news'
                    | 'events'
                    | 'sponsorship'
                    | 'donorPortal'
                    | 'studentPortal'
                    | 'alumniPortal'
                    | 'search'
                    | 'accounts'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legal?:
    | {
        label: string;
        /**
         * Path ("/academics/courses") or full URL
         */
        href: string;
        newTab?: boolean | null;
        /**
         * Hide when this module is off
         */
        feature?:
          | (
              | 'admissions'
              | 'donations'
              | 'zakatCalculator'
              | 'blog'
              | 'notices'
              | 'gallery'
              | 'downloads'
              | 'faq'
              | 'fatwa'
              | 'clarifications'
              | 'library'
              | 'books'
              | 'researchProjects'
              | 'videos'
              | 'news'
              | 'events'
              | 'sponsorship'
              | 'donorPortal'
              | 'studentPortal'
              | 'alumniPortal'
              | 'search'
              | 'accounts'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Figures shown on the home page. Please confirm with the office: the alumni total (293) does not match the batch totals (104) in the source document.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats".
 */
export interface ImpactStat {
  id: number;
  stats?:
    | {
        label: string;
        value: number;
        /**
         * "+" for “and more”; leave empty for an exact count
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The home page, section by section. Drag the rows to reorder the page; untick a section to hide it. Which programmes and people appear is chosen on the course / person themselves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * One block per section, in display order.
   */
  sections?:
    | (
        | {
            enabled?: boolean | null;
            /**
             * The large serif headline. Only the hero headline may be centred; nothing else competes with it.
             */
            heading: string;
            /**
             * One-line statement of purpose beneath the headline (reading text).
             */
            tagline?: string | null;
            /**
             * Optional intro video (YouTube URL). Shown as a poster that plays on click (GAP-C6).
             */
            videoUrl?: string | null;
            /**
             * Poster frame for the video. While there is no video, the hero stays typographic.
             */
            posterImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            enabled?: boolean | null;
            /**
             * Section heading. The figures come from Site ▸ Impact stats.
             */
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'impactStats';
          }
        | {
            enabled?: boolean | null;
            /**
             * e.g. মূল লক্ষ্য (Vision)
             */
            heading: string;
            /**
             * The vision statement, verbatim from the client document.
             */
            statement: string;
            /**
             * Three pillars under the statement. Empty in Bangla until the office provides translations.
             */
            pillars?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'vision';
          }
        | {
            enabled?: boolean | null;
            /**
             * The six featured programmes (cards) — the one place cards belong. Which courses appear is set per course (featured flag).
             */
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programmes';
          }
        | {
            enabled?: boolean | null;
            /**
             * Intellectual refutations highlight. Renders nothing until the clarifications module exists (REQ-HOME-05).
             */
            heading: string;
            /**
             * Draft copy for when the module is ready.
             */
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'refutations';
          }
        | {
            enabled?: boolean | null;
            /**
             * Latest notices with plain category tabs.
             */
            heading: string;
            /**
             * How many notices per tab.
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'notices';
          }
        | {
            enabled?: boolean | null;
            /**
             * Campus life as a ruled two-column list.
             */
            heading: string;
            /**
             * The document marks photo slots; upload them per item when photos arrive (GAP-C6).
             */
            items?:
              | {
                  title: string;
                  body: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campusLife';
          }
        | {
            enabled?: boolean | null;
            /**
             * Latest articles, videos, gallery. Renders nothing until the media modules exist (REQ-HOME-08).
             */
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaHub';
          }
        | {
            enabled?: boolean | null;
            /**
             * Featured leadership and faculty. Which people appear is set per person (featured on home flag).
             */
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'people';
          }
        | {
            enabled?: boolean | null;
            /**
             * A single calm band leading to the donation page.
             */
            heading: string;
            /**
             * One or two lines of context (the Zakat Fund scholarship line works well).
             */
            body?: string | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'support';
          }
        | {
            enabled?: boolean | null;
            /**
             * Quick ask box and fatwa bank entry. Renders nothing until the fatwa module exists (REQ-HOME-11).
             */
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fatwa';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  parentLine?: T;
  parentUrl?: T;
  logo?: T;
  prospectus?: T;
  phones?:
    | T
    | {
        number?: T;
        note?: T;
        id?: T;
      };
  email?: T;
  addresses?:
    | T
    | {
        label?: T;
        text?: T;
        mapUrl?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  admissionQr?: T;
  otherWebsites?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  features?:
    | T
    | {
        admissions?: T;
        donations?: T;
        zakatCalculator?: T;
        blog?: T;
        notices?: T;
        gallery?: T;
        downloads?: T;
        faq?: T;
        fatwa?: T;
        clarifications?: T;
        library?: T;
        books?: T;
        researchProjects?: T;
        videos?: T;
        news?: T;
        events?: T;
        comments?: T;
        sponsorship?: T;
        donorPortal?: T;
        recurring?: T;
        international?: T;
        campaigns?: T;
        studentPortal?: T;
        alumniPortal?: T;
        facebookFeed?: T;
        search?: T;
        accounts?: T;
        darkMode?: T;
      };
  defaultDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        feature?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              feature?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  utility?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        feature?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        feature?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        suffix?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              enabled?: T;
              heading?: T;
              tagline?: T;
              videoUrl?: T;
              posterImage?: T;
              id?: T;
              blockName?: T;
            };
        impactStats?:
          | T
          | {
              enabled?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        vision?:
          | T
          | {
              enabled?: T;
              heading?: T;
              statement?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        programmes?:
          | T
          | {
              enabled?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        refutations?:
          | T
          | {
              enabled?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        notices?:
          | T
          | {
              enabled?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        campusLife?:
          | T
          | {
              enabled?: T;
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaHub?:
          | T
          | {
              enabled?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        people?:
          | T
          | {
              enabled?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        support?:
          | T
          | {
              enabled?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        fatwa?:
          | T
          | {
              enabled?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}